name: worldcosts
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  http: ^1.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  leak_tracker: 10.0.8          # Exact version matching flutter_test
  leak_tracker_testing: 3.0.1   # Required by flutter_test
  leak_tracker_flutter_testing: 3.0.9  # Compatible version
  async: ^2.12.0
  fake_async: 1.3.2

flutter:
  uses-material-design: true